services:
  postgres:
    image: postgres:17-alpine
    container_name: subscriptions
    environment:
      POSTGRES_DB: subscriptions
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d subscriptions" ]
      interval: 2s
      timeout: 2s
      retries: 5
    networks:
      - subscriptions-net

  app:
    build: .
    container_name: subscriptions_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/subscriptions
      DB_USER: myuser
      DB_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - subscriptions-net

networks:
  subscriptions-net:
     driver: bridge

volumes:
    postgres_data: